# Generated by Django 4.2.11 on 2025-08-19 16:37

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250812_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Recommended size: 1200x630px for social media', null=True, upload_to='blog/featured/'),
        ),
    ]
