# Generated by Django 4.2.11 on 2025-08-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourtranslation',
            name='meeting_points',
        ),
        migrations.AlterField(
            model_name='tourmeetingpoint',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_meeting_points', to='tours.tour'),
        ),
    ]
