# Generated by Django 4.2.11 on 2025-08-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_tourtranslation_meeting_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.CharField(blank=True, help_text="Geographic location (e.g., 'Alba, Piedmont, Italy')", max_length=200, verbose_name='Tour Location'),
        ),
    ]
